---

#- fail: msg="This role is only compatible with Ubuntu Trusty and Xenial"
- debug: msg="This role is only compatible with Ubuntu Trusty and Xenial (ppa) and Fedora (COPR)"
  when: not (ansible_distribution == 'Ubuntu' and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial'))

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
  
- name: adding Gift stable repository
  apt_repository: repo='ppa:gift/stable' state=present
  register: repo

- name: update apt cache
  apt: update_cache=yes
  when: repo.changed
