---

- name: RedHat | Ensure dnf-plugins-core is present
  package:
    name: dnf-plugins-core
    state: present

# https://github.com/ansible/ansible/issues/26673
- name: RedHat | Enable GIFT Copr
  command: "dnf copr enable -y @gift/stable"
  args:
    creates: /etc/yum.repos.d/_copr_@gift-stable.repo
  warn: no
