---

- name: Debian/Ubuntu | Setting webupd8 repository
  apt_repository:
    repo: 'ppa:webupd8team/java'
    codename: 'xenial'
    update_cache: yes

- name: Ensure Java is installed.
  apt: "name={{ item }} state=present"
  with_items: "{{ java_packages }}"
