# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    #config.vm.box = "centos/7"

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.become = true
       ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
       ansible.groups = {
          "myhost" => ["vtimesketch" ],
       }
    end

    config.vm.define "vtimesketch" do |vtimesketch|
        vtimesketch.vm.hostname = "vtimesketch"
        vtimesketch.vm.provider "virtualbox" do |v|
          ## 512 ok if swap
          v.memory = 1024
        end
        vtimesketch.vm.network "forwarded_port", guest: 5000, host: 15000
    end

end

